name: zzZzzz

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo ">>> Starting `date`"
      - name: Sleep
        run: |
          echo ">>> Sleeping for 3m"
          sleep 3m
      - name: Stop
        run: echo ">>> Stopping `date`"
          
